// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwgnaikxzsdarejsdcmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3Z25haWt4enNkYXJlanNkY21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNTA1MjUsImV4cCI6MjA3NDcyNjUyNX0.JvQm-rqEzrRHuy9GLi7kPM2HOjhGOlK2KxlNDX1XCjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});